# Generated by Django 3.1 on 2020-08-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_img',
            field=models.ImageField(upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
