# Generated by Django 3.1 on 2020-08-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200819_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ab_title', models.CharField(max_length=50)),
                ('ab_subtext', models.CharField(max_length=1000)),
                ('ab_img', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
